### ISSUE TITLE
Internal Error from Ubuntu

### ISSUE THREAD

**Issue by boasbakker** [ioi-2023/contestant-vm#82] opened 2023-08-05 16:11 UTC
**Describe the bug**
I get this 'Internal Error' from Ubuntu when trying to download coreputer.zip and coreputer (en).pdf.

**To Reproduce**
I have not yet tried to reproduce this behaviour.

**Expected behavior**
No error would appear.

**Screenshots**
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/3108b1ca-9eba-48ac-b13e-ba088c1d0eba)
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/14913531-b407-4270-9809-2a2bed22e9ec)
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/4f863ea1-0deb-47b0-89a8-528034e6bf97)
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/a423ab78-4227-4126-8213-fe7e37dc23bc)
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/396dd61a-1fbf-4d62-9fed-62e67ee6f7c5)
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/6157b6dc-dbb9-46b3-80ab-db4a11a9ab0a)
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/601255e7-980b-4567-9aee-d6fe5068f83a)
![image](https://github.com/ioi-2023/contestant-vm/assets/59883944/2282e6d6-99e2-4b83-9c2b-e63e97c867b3)

**Please complete the following information:**

 - For pre-built, image release version: contestant-vm-0804.ova

**Additional context**
I'll try to reproduce it with a new install of the VM.

**Comment by radl97** [comment] 2023-08-05 16:37
Duplicate of #35

**Closed by radl97** 2023-08-05 16:37 UTC
Labels: bug
